### PR TITLE
Support Kline/Candlestick stream for Binance Coin-margined Futures

### PR DESCRIPTION
**Pull request by trexnix**
Support Kline/Candlestick stream for [Binance Coin-margined Futures](https://binance-docs.github.io/apidocs/delivery/en/#kline-candlestick-streams).

An example of use:

```python3
from cryptofeed import FeedHandler
from cryptofeed.defines import CANDLES
from cryptofeed.exchanges import BinanceDelivery

async def candle_callback(feed, symbol, start, stop, interval, trades, open_price, close_price, high_price, low_price, volume, closed, timestamp, receipt_timestamp):
    print(f"Candle: {timestamp} {receipt_timestamp} Feed: {feed} Symbol: {symbol} Start: {start} Stop: {stop} Interval: {interval} Trades: {trades} Open: {open_price} Close: {close_price} High: {high_price} Low: {low_price} Volume: {volume} Candle Closed? {closed}")

def main():
    config = {'log': {'filename': 'demo.log', 'level': 'INFO'}}
    f = FeedHandler(config=config)
    pairs = ["DOGE-USD_PERP"]
    f.add_feed(BinanceDelivery(symbols=pairs, channels=[CANDLES], callbacks={CANDLES: candle_callback}))

    f.run()

if __name__ == '__main__':
    main()
```

### CODE REVIEW

**Comment by bmoscon** [comment]
@trexnix did you mean to close this?

**Comment by trexnix** [comment]
Oh, that was fast. If it looks good to you, I would be happy if this got merged into your repository. I intended to test it in my fork only as I'm not sure if you're interested in it 😅

**Comment by bmoscon** [comment]
I'm about 99% sure thats the only change needed. You might want to test though. The only other thing it might need is the candle interval added to the init signature.

**Comment by bmoscon** [comment]
but yes, will merge it, if you confirm it works / is tested

**Comment by trexnix** [comment]
Thanks for your replies 🙇 

> I'm about 99% sure thats the only change needed. You might want to test though. The only other thing it might need is the candle interval added to the init signature.

Sorry, isn't `BinanceDelivery` is inherited from `Binance` thus it technically has `candle_interval` in its `init` already? 🤔 

I tested it with the following setup:
```
f.add_feed(BinanceDelivery(symbols=pairs, channels=[CANDLES], callbacks={CANDLES: candle_callback}, candle_interval='5m'))
```

and it works without adding anymore code.

**Comment by bmoscon** [comment]
yep - just confirmed this is the case. Looks good - thanks!

**Review by bmoscon — APPROVED** [review]

**Comment by trexnix** [comment]
Cool, thanks a lot @bmoscon 🙇

**Pull request merged**
