### PR TITLE
handle level3 book differently

### PR DESCRIPTION
**Pull request by wangzhe3224**
### Description of code - what bug does this fix / what feature does this add?

`to_dict` method of OrderBook for level 3 throw exceptions when passing `as_type` as float. 

current fix is to create a different code branch for level 3.

here is a test code to show the issue and fix:

``` Python
from cryptofeed import FeedHandler
from cryptofeed.callback import BookCallback
from cryptofeed.defines import BID, ASK, L2_BOOK, L3_BOOK
from cryptofeed.exchanges import (Coinbase, Bitfinex)


async def test_book(book, receipt_timestamp):
    print(f'Book received at {receipt_timestamp} for {book.exchange} - {book.symbol}, with {len(book.book)} entries. Top of book prices: {book.book.asks.index(0)[0]} - {book.book.bids.index(0)[0]}')
    if book.delta:
        print(len(book.to_dict(as_type=float)))

config = {'log': {'filename': 'demo.log', 'level': 'INFO'}}
f = FeedHandler(config=config)
f.add_feed(Coinbase(symbols=['BTC-USDT'], channels=[L3_BOOK], callbacks={L3_BOOK: BookCallback(test_book)}))
f.add_feed(Bitfinex(symbols=['BTC-USDT'], channels=[L3_BOOK], callbacks={L3_BOOK: BookCallback(test_book)}))
f.run()
```

- [x] - Tested
- [x] - Changelog updated
- [x] - Tests run and pass
- [x] - Flake8 run and all errors/warnings resolved
- [ ] - Contributors file updated (optional)

### CODE REVIEW

**Comment by bmoscon** [comment]
I appreciate this PR, but I think I'm going to add support for this in the underlying c library - it will be far less complicated and much less ugly. I'm not positive it will work there though, so I'll leave this PR open until I confirm it will work. Assuming it does, I'll close this, if it doesnt i'll merge this

**Comment by wangzhe3224** [comment]
> I appreciate this PR, but I think I'm going to add support for this in the underlying c library - it will be far less complicated and much less ugly. I'm not positive it will work there though, so I'll leave this PR open until I confirm it will work. Assuming it does, I'll close this, if it doesnt i'll merge this

agreed, idealy `to_dict` here should just be `to_dict` in the OrderBook module. It is a bit odd to put many lines in the wrapper class as a not nice walk around.

**Comment by bmoscon** [comment]
@wangzhe3224 - should be fixed now, give the latest code from github a try and let me know what you think or if you have any issues

**Comment by wangzhe3224** [comment]
> @wangzhe3224 - should be fixed now, give the latest code from github a try and let me know what you think or if you have any issues

Hi, it seems still has some issue when running above test code. I did pull master and `python setup.py develop`. It looks like the line here: `return {'exchange': self.exchange, 'symbol': self.symbol, 'delta': {BID: [(as_type(price), as_type(size)) for price, size in self.delta[BID]], ASK: [(as_type(price), as_type(size)) for price, size in self.delta[ASK]]} if self.delta else None, 'timestamp': self.timestamp}
`

```
2021-09-17 07:27:10,026 : ERROR : BITFINEX.ws.3: encountered an exception, reconnecting in 1.0 seconds
Traceback (most recent call last):
  File "/Users/zhewang/Projects/cryptofeed/cryptofeed/connection_handler.py", line 68, in _create_connection
    await self._handler(connection, self.handler)
  File "/Users/zhewang/Projects/cryptofeed/cryptofeed/connection_handler.py", line 117, in _handler
    await handler(message, connection, self.conn.last_message)
  File "/Users/zhewang/Projects/cryptofeed/cryptofeed/exchanges/bitfinex.py", line 307, in message_handler
    await chan_handler(msg, timestamp)
  File "/Users/zhewang/Projects/cryptofeed/cryptofeed/exchanges/bitfinex.py", line 281, in _raw_book
    await self.book_callback(L3_BOOK, self._l3_book[pair], timestamp, raw=msg, delta=delta, sequence_number=msg[-1])
  File "/Users/zhewang/Projects/cryptofeed/cryptofeed/feed.py", line 181, in book_callback
    await self.callback(book_type, book, receipt_timestamp)
  File "/Users/zhewang/Projects/cryptofeed/cryptofeed/feed.py", line 192, in callback
    await cb(obj, receipt_timestamp)
  File "/Users/zhewang/Projects/cryptofeed/cryptofeed/callback.py", line 20, in __call__
    await self.callback(obj, receipt_timestamp)
  File "/Users/zhewang/Projects/cryptofeed/instance/my_t1.py", line 10, in test_book
    print(len(book.to_dict(as_type=float)))
  File "cryptofeed/types.pyx", line 296, in cryptofeed.types.OrderBook.to_dict
ValueError: too many values to unpack (expected 2)
```

**Comment by bmoscon** [comment]
@wangzhe3224 - alright, I fixed the deltas too. Take a look and let me know what you think.

**Comment by wangzhe3224** [comment]
@bmoscon thanks! looks good to me now. Happy to close PR.

**Pull request closed without merging**
