### PR TITLE
Support for Bybit spot websocket endpoints

### PR DESCRIPTION
**Pull request by kieran-mackle**
### Description of code - what bug does this fix / what feature does this add?
Added support for spot websocket endpoints on Bybit. Current implementation includes [trade](https://bybit-exchange.github.io/docs/spot/v3/#t-websockettrade) and [orderbook](https://bybit-exchange.github.io/docs/spot/v3/#t-websocketdepth) channels.

### Testing
To connect to a spot endpoint, specify a standardised spot symbol. See example code below, connecting to both spot and perpetual endpoints for trades and orderbook. 

```python
from decimal import Decimal
from cryptofeed import FeedHandler
from cryptofeed.exchanges import Bybit
from cryptofeed.defines import TRADES, L2_BOOK, BID, ASK


async def book(book, receipt_timestamp):
    print(f'Book received at {receipt_timestamp} for {book.exchange} - {book.symbol}, with {len(book.book)} entries. Top of book prices: {book.book.asks.index(0)[0]} - {book.book.bids.index(0)[0]}')
    if book.delta:
        print(f"Delta from last book contains {len(book.delta[BID]) + len(book.delta[ASK])} entries.")
    if book.sequence_number:
        assert isinstance(book.sequence_number, int)


async def trade(t, receipt_timestamp):
    assert isinstance(t.timestamp, float)
    assert isinstance(t.side, str)
    assert isinstance(t.amount, Decimal)
    assert isinstance(t.price, Decimal)
    assert isinstance(t.exchange, str)
    print(f"Trade received at {receipt_timestamp}: {t}")


def main():
    f = FeedHandler()
    f.add_feed(Bybit(symbols=["ETH-USDT", "ETH-USDT-PERP"], channels=[TRADES, L2_BOOK], callbacks={TRADES: trade, L2_BOOK: book}))
    f.run()


if __name__ == '__main__':
    main()
```

- [x] - Tested
- [x] - Changelog updated
- [x] - Tests run and pass
- [x] - Flake8 run and all errors/warnings resolved
- [x] - Contributors file updated (optional)

### CODE REVIEW

**Review by bmoscon — CHANGES_REQUESTED** [review]
I'm not sure what formatting tool you used, but undo all the un-necessary formatting changes and then I will review the real changes

**Comment by kieran-mackle** [comment]
@bmoscon I used Black. Formatting changes reverted, ready for review.

**Comment by bmoscon** [comment]
formatting changes persist, will review once they have been resolved

**Comment by bastienjalbert** [comment]
@bmoscon Are there still formatting issues?

**Comment by bmoscon** [comment]
@bastienjalbert - there was a merge conflict - i resolved it but now the tests are failing. if @kieran-mackle can fix them I will merge it. I can take a look at fixing them myself but might not get time for a few days. likely the test data for bybit needs to be regenerated and then the expected callback counts will need to be updated in the test case. that may not be all though

**Comment by adamlansky** [comment]
Hey @kieran-mackle I would love to see this merged - do you think you could look into merge conflict @bmoscon mentioned? Please let me know if you could use a hand here, I would be more than happy to contribute 👍🏼

**Comment by bastienjalbert** [comment]
Hello @bmoscon, do you need help to finally merge this PR ?

**Comment by bmoscon** [comment]
@bastienjalbert the tests are failing, if they are fixed, I will merge it, otherwise at some point in the not too distant future I'll close this PR

**Comment by bmoscon** [comment]
@bastienjalbert let me know if you are still working on this

**Comment by bastienjalbert** [comment]
@bmoscon 
Hard to find time lately. I’ll probably work on it, but in fews months.

**Comment by bmoscon** [comment]
@bastienjalbert feel free to fork off this PR and open a new one when you have time to take it on.

**Pull request closed without merging**
