### PR TITLE
Add support for OHLCV callback (arctic only)

### PR DESCRIPTION
**Pull request by ph4z**
### Description of code - what bug does this fix / what feature does this add?

Add support for OHLCV callback for arctic.

- [X] - Tested
- [ ] - Changelog updated
- [ ] - Tests run and pass
- [ ] - Flake8 run and all errors/warnings resolved
- [ ] - Contributors file updated (optional)

### CODE REVIEW

**Comment by ph4z** [comment]
Hi @bmoscon, is there something wrong with this PR ?

**Comment by bmoscon** [comment]
@ph4z I havent had a chance to test it out. You're changing some function signatures so its something I'll need to evaluate, also any time a backend changes, they all need to change. you cant add it just for arctic, it would need to be added to all the other backends so they all have feature parity

**Comment by ph4z** [comment]
Can you give me more details about the function signatures ? Do I need to change something ?
Concerning other backends, I might add influxdb support soon.

**Comment by bmoscon** [comment]
@ph4z I went to take a look at this again, but it looks like something weird happened when you merged the main repo back into your fork. Can you fix this or recreate the changes in a new fork?

**Comment by ph4z** [comment]
Hi, yes it seems I  pushed other commits in this branch by error.
I'll take a look on it soon.

**Comment by bmoscon** [comment]
@ph4z since I've added support directly for candles, I'm not sure this code is needed. If anything, more effort should be put into adding support for the other exchanges that support candles (like Huobi and others). I'm going to close this, but feel free to re-open if you ever want to revisit and address the changes I requested above

**Pull request closed without merging**
