### PR TITLE
Use orjson for json

### PR DESCRIPTION
**Pull request by vincentmele**
Orjson is 2x to 4x faster for json parsing over the standard json library in general cases. I have not benchmarked it specifically with cryptofeed but there is no reason to believe those results will not hold up. 

This change replaced all "import json" lines with "import orjson as json", and added orjson as a requirement to setup.py.

### CODE REVIEW

**Comment by bmoscon** [comment]
@vincentmele looks cool - thanks! I'm going to pull this and test it for a bit before merging since its such a large change.

**Comment by vincentmele** [comment]
Annnd, I may have jumped the gun. What I thought I was thoroughly testing turns out to have been old code, and orjson is throwing errors all over the place. I will investigate, fix, and provide an update in the next day or so.

**Comment by bmoscon** [comment]
one thing to note @vincentmele - orjson doesnt support parsing to decimal.Decimal, this could be an issue. I belive ujson supports this

**Comment by vincentmele** [comment]
Great observation about parsing to decimal.Decimal. orjson definitely doesn't support it, and ujson appears to not support decoding to decimal. 

yapic.json (https://github.com/zozzz/yapic.json/), which I see you've already forked :-), appears to be a drop in replacement that supports decoding to decimal. I've successfully run examples/demo.py, this time double checking that I was using the correct site-packages,

**Comment by vincentmele** [comment]
From the yapic.json benchmark (completely unscientific), the conversion times for float to decimal are very close between the standard library and yapic. This is likely because Python 3.3+ already uses the optimised cdecimal library.

```
List of float values to Decimal (rounds: 100, iterations: 100)                                   |
  Title                     Min            Max           Mean         StdDev         Call/sec 
  DECODE ->
    yapic              106.10429       196.78091       118.57315        19.49395           0.84336
    python             115.41666       130.51549       120.96007         3.34905           0.82672
    rapidjson     error: 'use_decimal' is an invalid keyword argument for rapidjson.loads()```

I'm curious to dump some traffic from exchanges and do a proper benchmark with cryptofeed, as this may all be for minimal improvements, which IMHO wouldn't be worth moving away from the standard library.

**Comment by vincentmele** [comment]
I have to say, thank you for making this easy. I dumped raw json data using examples/demo_raw_data.py, and then used it in the test below. The results show yapic is about 1.3x to 2.1x the speed of the standard library for parsing l2_book, ticker, and trades data from 100 MB files from Binance and Deribit feeds.

Based on these results, I am going to proceed with integrating yapic for further stability testing.

```
binance results
file lines: 211316
yapic: 13.38 seconds
json: 23.62 seconds
yapic lps: 47390.76 lines per second
json lps: 26838.02 lines per seond
json/yapic: 1.77x

deribit results
file lines: 310000
yapic: 18.85 seconds
json: 37.63 seconds
yapic lps: 49332.11 lines per second
json lps: 24717.06 lines per seond
json/yapic: 2.00x

```


```
import joblib
import timeit

iterations = 3
files =  { 'binance' : 'BINANCE12f2ac65-b5c5-404d-b8b4-8f22c04da3a4.0',
           'deribit' : 'DERIBIT252a6e79-7a32-4038-a64a-b1f7b29d6837.3' }

def load_file(filepath):
  output = []
  with open(filepath) as fp:
    line = fp.readline()
    while line:
      output.append(line.split(' ')[1])
      line = fp.readline()
  joblib.dump(output, 'json.pkl')
  return len(output)

for k, f in files.items():
  length = load_file(f)
  yapic_time = timeit.timeit('[json.loads(msg,parse_float=Decimal) for msg in txt]',setup="from yapic import json; import joblib; from decimal import Decimal; txt = joblib.load('json.pkl')", number=iterations)
  yapic_lps = length * iterations / yapic_time

  json_time = timeit.timeit('[json.loads(msg,parse_float=Decimal) for msg in txt]',setup="import json; import joblib; from decimal import Decimal; txt = joblib.load('json.pkl')", number=iterations)
  json_lps = length * iterations / json_time

  ratio = json_time / yapic_time

  print(f'{k} results')
  print(f'file lines: {length}')
  print(f'yapic: {yapic_time:.2f} seconds')
  print(f'json: {json_time:.2f} seconds')
  print(f'yapic lps: {yapic_lps:.2f} lines per second')
  print(f'json lps: {json_lps:.2f} lines per seond')
  print(f'json/yapic: {ratio:.2f}x')

```

**Comment by vincentmele** [comment]
Closed this request as I prematurely submitted it before it was ready. See issue #231.

**Pull request closed without merging**
