### PR TITLE
Bitmex and Deribit pairs

### PR DESCRIPTION
**Pull request by Quenos**

### CODE REVIEW

**Comment by Quenos** [comment]
Only wanted to commit one file

**Comment by bmoscon** [comment]
@Quenos just one file? Looks like some good stuff in here!

**Comment by Quenos** [comment]
@bmoscon  Good stuff indeed, all my API keys exposed 🗡️ 
But all deleted now. Really need to learn git better.

Will do some changes, removing the personal stuff and re-submit.

**Comment by bmoscon** [comment]
@Quenos  oh, I didn't even notice that, I just saw lots of work to the rest api feeds! Clean up and resubmit - sounds excellent

**Pull request closed without merging**
