### PR TITLE
only install yapic.json on CPython

### PR DESCRIPTION
**Pull request by oberstet**
fix for #777 .. not yet complete

### CODE REVIEW

**Comment by oberstet** [comment]
alright, this is getting somewhere:

```
(pypy38_1) (base) oberstet@intel-nuci7:~/scm/oberstet/cryptofeed$ pypy ~/scm/3rdparty/cryptofeed/examples/demo.py 
****************************************************************************************************
['BTC', 'BUSD', 'DAI', 'ETH', 'USD', 'USDC', 'USDT']
****************************************************************************************************
['1INCH',
 'AAVE',
 'ADA',
 'ALGO',
 'ATOM',
 'AVAX',
 'BCH',
 'BTC',
 'COMP',
 'CRV',
 'DOGE',
 'DOT',
 'EOS',
 'ETH',
 'FIL',
 'LINK',
 'LTC',
 'MATIC',
 'MKR',
 'SNX',
 'SOL',
 'SUSHI',
 'UMA',
 'UNI',
 'XMR',
 'YFI',
 'ZEC',
 'ZRX']
****************************************************************************************************
BinanceFutures 32
Bitfinex       24
Coinbase       68
dYdX           28
FTX            27
HuobiSwap      23
OKEx           49
****************************************************************************************************
```

**Comment by oberstet** [comment]
mmh. ok. disappointing. it works on pypy (apart from 2 minor issues below), but my program is slower. I suspect the massive use of Cython - which creates native code extensions for the CPyExt API of CPython, which needs to be "simulated" on PyPy. fwiw, the modern way is CFFI. 

IOW: forget my PR, moot:(

I was hoping to be able to reuse your awesome library "as is".

thanks btw for your work and providing it as OSS!


```
2022-02-08 03:16:10,592 : ERROR : COINBASE.ws.9: encountered an exception, reconnecting in 4.0 seconds
Traceback (most recent call last):
  File "/home/oberstet/scm/oberstet/cryptofeed/cryptofeed/connection_handler.py", line 61, in _create_connection
    await self.subscribe(connection)
  File "/home/oberstet/scm/oberstet/cryptofeed/cryptofeed/exchanges/coinbase.py", line 384, in subscribe
    "channels": [chan]
  File "/home/oberstet/pypy3.8-v7.3.7-linux64/lib/pypy3.8/json/__init__.py", line 237, in dumps
    return _default_encoder.encode(obj)
  File "/home/oberstet/pypy3.8-v7.3.7-linux64/lib/pypy3.8/json/encoder.py", line 190, in encode
    self.__encode(o, markers, builder, 0)
  File "/home/oberstet/pypy3.8-v7.3.7-linux64/lib/pypy3.8/json/encoder.py", line 235, in __encode
    self.__encode_dict(o, markers, builder, _current_indent_level)
  File "/home/oberstet/pypy3.8-v7.3.7-linux64/lib/pypy3.8/json/encoder.py", line 300, in __encode_dict
    self.__encode(v, markers, builder, _current_indent_level)
  File "/home/oberstet/pypy3.8-v7.3.7-linux64/lib/pypy3.8/json/encoder.py", line 238, in __encode
    res = self.default(o)
  File "/home/oberstet/pypy3.8-v7.3.7-linux64/lib/pypy3.8/json/encoder.py", line 174, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type set is not JSON serializable
```


```
2022-02-08 03:16:10,592 : ERROR : COINBASE.ws.9: encountered an exception, reconnecting in 4.0 seconds
Traceback (most recent call last):
  File "/home/oberstet/scm/oberstet/cryptofeed/cryptofeed/connection_handler.py", line 61, in _create_connection
    await self.subscribe(connection)
  File "/home/oberstet/scm/oberstet/cryptofeed/cryptofeed/exchanges/coinbase.py", line 384, in subscribe
    "channels": [chan]
  File "/home/oberstet/pypy3.8-v7.3.7-linux64/lib/pypy3.8/json/__init__.py", line 237, in dumps
    return _default_encoder.encode(obj)
  File "/home/oberstet/pypy3.8-v7.3.7-linux64/lib/pypy3.8/json/encoder.py", line 190, in encode
    self.__encode(o, markers, builder, 0)
  File "/home/oberstet/pypy3.8-v7.3.7-linux64/lib/pypy3.8/json/encoder.py", line 235, in __encode
    self.__encode_dict(o, markers, builder, _current_indent_level)
  File "/home/oberstet/pypy3.8-v7.3.7-linux64/lib/pypy3.8/json/encoder.py", line 300, in __encode_dict
    self.__encode(v, markers, builder, _current_indent_level)
  File "/home/oberstet/pypy3.8-v7.3.7-linux64/lib/pypy3.8/json/encoder.py", line 238, in __encode
    res = self.default(o)
  File "/home/oberstet/pypy3.8-v7.3.7-linux64/lib/pypy3.8/json/encoder.py", line 174, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type set is not JSON serializable
```

**Comment by oberstet** [comment]
just for completeness, here is my test program on CPython maxing out with at peak ~25Mbps infeed .. need to find another way


Bildschirmfoto von 2022-02-08 03-20-25

**Comment by bmoscon** [comment]
I've never heard of CFFI but I took a look at it. Modern or not, that looks terrible. I'll stick with cython or the C API :D

**Comment by oberstet** [comment]
all good! I'm happy to have some OSS code to start from with cryptofeed. I am not complaining;) so pls take below just as some personal comments from a random Python developer ..

> Modern or not, that looks terrible.

I don't understand that part, as CFFI "doesn't look" itself: "The CFFI design requires users to know only C and Python, minimizing the extra bits of API that need to be learned."

The Python community has been fighting with this for quite a time, whole projects sprung up, eg https://pythoncapi.readthedocs.io/cpyext.html which back/cross-ports cpyext to PyPy, or pythoncapi, which is the umbrella project to redo the whole API for both CPython and PyPy.

my view: this is all welcome and needed, and will make practical progress. other things will never get "fixed": the GIL namely. Well, that's life;)

> Of course if you were so motivated and wanted to remove the cython code

fwiw, I am looking at different options of how to move forward now .. actually, I would like to have my reconstructed orderbook in LMDB stored in NumPy arrays (which I have as a separate project working), but need to see if I can spill out orderbook updates on that fast enough .. still experimenting, shuffling code around.

using cryptofeed, I now could measure the load of the infeed, roughly 10-20Mbps or 10k msgs/s from 8 exchanges / 270 pairs .. anyways, making progress ...

**Comment by bmoscon** [comment]
I've multiprocessed to get around the limitations you mention, hasn't been a big issue for me

**Comment by bmoscon** [comment]
as far as CFFI looking terrible - thats just my opinion obviously after 5 mins of looking at code samples. Seeing C code wrapped in python strings just felt bizarre and unnecessary given the other options out there. I'm sure there are some solid CFFI modules out there, but for me, knowing Cython and having a background in C, I don't see the advantage or draw of it.

**Comment by oberstet** [comment]
rgd CFFI: it stems from a different angle. say you have an existing C library with C headers that exists as its own project. now you want to access that from Python. this is what _one_ of the modes of CFFI is optimized for:

https://cffi.readthedocs.io/en/latest/overview.html#main-mode-of-usage

thus, you don't usually write much C in CFFI, but just include the existing C headers of the lib.

Cython was written with this as a premise: Python code itself is slow, and there should be an easy way of compiling the Python code itself to C to make it fast.

This part is unneeded and unwanted in PyPy, since that is a JIT that will spill out _machine_ code that runs faster than the one coming from the C compiler.

And: it is _tracing_, which means, it will reoptimize and recompile your code automatically _while_ your program is running, and _while_ the input to your program changes (and hence, the optimal compilation changes). Hot paths are JIT'ed on the fly. A C compiler cannot do that. Not GCC. Not LLVM. Anyways, details ..

> hasn't been a big issue for me

let's make it concrete: how do you share an in-memory representation of an order book between multiple processes?

* with no serialized/deserialization overhead, no context switches and no locks
* for a single process/thread writer and multiple readers
* where readers don't block the writer, and the writer doesn't block the reader.

and from Python.

cryptofeed has a Cython order book object running in a CPython process .. and that object cannot be accessed from another CPython process directly ...

what I am using is: LMDB (which is available wrapped in CFFI) with value type NumPy array, and I can access that with zero-copy and zero-deserialization from multiple processes .. LMDB mmap's a writable file into multiple processes. anyways, I understand we are now talking about a much broader scoped thing .. the whole "app" ..

**Comment by bmoscon** [comment]
ok, that makes more sense. The tutorials I was looking at were probably not the best at illustrating the true purpose / power of CFFI. Anyways, for this project, I'm basically keeping the data in dicts anyways, and I didnt want to have to convert back and forth so that was a reason for using the C-API and cython. 

I don't process the data in the process that collects it. It seems more like you want all the data in a single process for some purpose (data analysis, trading algorithm, etc). My approach is more of a microservices type system where the data collection processes do just that, and that alone. The data is aggregated and processed elsewhere. 

If you want to discuss further, feel free to email me - the email is in the github profile and in the license file.

**Comment by oberstet** [comment]
@bmoscon for completeness, and as we've started above discussion on the general cpyext/pypy performance questions, let me just post my current findings here (sorry, pls let me know if this should be a separate issue / mailing list post or sth ..)

1. I now have code for data feed (trades & orders) from exchanges that runs without CPyExt stuff, and hence fast on PyPy. Now I need an orderbook .. just to collect up the orders.
2. I found https://github.com/bmoscon/orderbook/blob/main/perf/performance_test.py which I tested to compare CPython and PyPy. Here are the results:
   * **CPython fastest: C lib OrderBook  @ 0.06758761405944824**
   * **PyPy fastest: Python OrderBook @ 0.09093928337097168**
3. I haven't changed anything in the perf test apart from 5x looping over the test. This is to allow PyPy to JIT the code and produces stable results. As I expected, the pure Python code is fastest on PyPy - but it is slightly slower the the Cython code on CPy :(
4. I also want to test (unmodified) with Numba, but I don't expect anything earth shattering .. and:
5. I'm wondering about your comment "This class is functionally equivalent to the C class (for the basic use cases)." in `pyorderbook.py` 
 
Ultimately, in what I'm building, the orderbook is just a (fixed) preprocessing step to fill in NumPy arrays of time vectors (eg for "best bid" or "best + 0.5% bid" in 100us steps).

I would expect the details of this last filling step (from orderbook to numpy arrays) to dominate the run-time.

**IOW: Does a question like "what's the fastest orderbook" make sense at all without specifying and fixing the queries/access pattern on the orderbook? and that latter part depends on the embedding application anyways? Would you agree with that?**

```
Orderbook Overall

C lib OrderBook
Time: 0.06758761405944824
Sortedcontainers OrderBook
Time: 0.14661860466003418
Python OrderBook
Time: 0.09811592102050781

(cpy39_1) (base) oberstet@intel-nuci7:~/scm/3rdparty/orderbook$ python -V
Python 3.9.4

Orderbook Overall

C lib OrderBook
Time: 0.157484769821167
Sortedcontainers OrderBook
Time: 0.09757757186889648
Python OrderBook
Time: 0.09093928337097168

(pypy38_1) (base) oberstet@intel-nuci7:~/scm/3rdparty/orderbook$ python -V
Python 3.8.12 (9ef55f6fc369, Oct 24 2021, 20:11:54)
[PyPy 7.3.7 with GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]
```

on

```
(pypy38_1) (base) oberstet@intel-nuci7:~/scm/3rdparty/orderbook$ git diff
diff --git a/perf/performance_test.py b/perf/performance_test.py
index dd91460..82d7594 100644
--- a/perf/performance_test.py
+++ b/perf/performance_test.py
@@ -127,13 +127,14 @@ def random_data_performance():


 if __name__ == "__main__":
-    print("Sorted Dict Performance\n")
-    random_data_performance()
-
-    print("\n\nOrderbook Overall\n")
-    print("C lib OrderBook")
-    profile_orderbook()
-    print("Sortedcontainers OrderBook")
-    profile_orderbook_sd()
-    print("Python OrderBook")
-    profile_orderbook_python()
+    for i in range(5):
+        print("Sorted Dict Performance\n")
+        random_data_performance()
+
+        print("\n\nOrderbook Overall\n")
+        print("C lib OrderBook")
+        profile_orderbook()
+        print("Sortedcontainers OrderBook")
+        profile_orderbook_sd()
+        print("Python OrderBook")
+        profile_orderbook_python()
```

**Comment by oberstet** [comment]
What queries are you running on your orderbook regularly?

Still trying to understand this ... currently, I'm thinking of the following queries for bids and asks on the book:

1. determine the best price
2. determine total interest (price*size) at any price
3. determine sum of interest (price*size) up to given price
4. given volume, determine the lowest price covering the volume with interest (that is, the price up to which an order of the given volume would eat into the orderbook)

**Pull request closed without merging**
