### PR TITLE
#813 Added Authenticatin for private channels on BITTREX. Added ORDER_INFO and BALANCES.

### PR DESCRIPTION
**Pull request by svabra**
### Description of code - what bug does this fix / what feature does this add?

- [x] - Tested
- [x] - Changelog updated
- [ ] - Tests run and pass
- [ ] - Flake8 run and all errors/warnings resolved
- [ ] - Contributors file updated (optional)

### CODE REVIEW

**Comment by svabra** [comment]
added change log.

**Comment by svabra** [comment]
The BEQUANT test should be adapted. It is not related to the contributed code.

**Comment by svabra** [comment]
@bmoscon Hi Bryant, is there a roadmap I could follow on when you release the next tag? It influences my timing on my contributions.

**Comment by bmoscon** [comment]
@svabra not really - when it seems like there are enough changes, or when its been long enough, I put out a release. Did you have something else in mind?

**Review by bmoscon — APPROVED** [review]

**Pull request merged**
