### PR TITLE
Merge Bmoscon/cryptofeed master

### PR DESCRIPTION
**Pull request by Dynamikey**

### CODE REVIEW

**Comment by bmoscon** [comment]
@Dynamikey - did you mean to close this? Looks like some good changes here

**Comment by Dynamikey** [comment]
> @Dynamikey - did you mean to close this? Looks like some good changes here

@bmoscon I did! I’d be keen to get some of these changes into the main repo however. Is there a procedure I can follow?

**Comment by bmoscon** [comment]
Just put the changes you want into a branch (in your repo) and then open a PR from that branch to this repository.

**Comment by bmoscon** [comment]
@Dynamikey - Just put the changes you want into a branch (in your repo) and then open a PR from that branch to this repository.

**Pull request closed without merging**
