### PR TITLE
Update setup.py

### PR DESCRIPTION
**Pull request by xiandong79**
add "zmq" requires

### CODE REVIEW

**Comment by bmoscon** [comment]
its an optional requirement, why does it need to be required? 

https://github.com/bmoscon/cryptofeed/blob/master/setup.py#L61

Its only needed if one wants to make use of the ZMQ functionality the backend provides

**Comment by xiandong79** [comment]
step1. I build the package of cryptostore + cryptofeed from source code in your Github.
step2. I run 'cryptostore --config my_config.yaml'. (I using Redis + influx + parquet backends)

I got 'ImportError: No module named zmq'. So it seems that it is a required package.

**Comment by bmoscon** [comment]
zmq is only needed if you have passthrough enabled in the config. If its in there, you'd need ZMQ. You can install it with cryptostore[zmq] which will install the extras

**Comment by xiandong79** [comment]
I do not need zmq as I am using Redis + influx + parquet as backends.

Do you mean that, I should comment following line in the config.yaml?
```
pass_through:
    type: zmq
    host: '127.0.0.1'
    port: 5678
```

**Comment by xiandong79** [comment]
I always do not know what is the meaning of 'pass_through'.

I just leave it alone as the default config.yaml does. I notice that I do not use elastic for storage, but I can just leave the config of elastic alone.

**Pull request closed without merging**
