### PR TITLE
Add RabbitMQ backend.

### PR DESCRIPTION
**Pull request by zhenpingfeng**

### CODE REVIEW

**Comment by bmoscon** [comment]
@zhenpingfeng any reason why you closed this? This looks solid - definitely something I'd take

**Comment by zhenpingfeng** [comment]
Have some typo, I will pull request later.

**Comment by bmoscon** [comment]
@zhenpingfeng ok great. One small thing though - is there a reason why you wouldnt use aio_pika? everything else in here relies on AIO

**Comment by zhenpingfeng** [comment]
Because pika is from the official site example, I will check out aio_pika library later.

**Pull request closed without merging**
