### PR TITLE
Update okex.py

### PR DESCRIPTION
**Pull request by bandito1**
Order channel changes: 'MARGIN' type not worked on Orders, changed to 'SPOT' and now is ok.
Added Positions channel (with 'MARGIN' type, because positions channel not work with 'SPOT')
I can't add Positions to types, because types are not public.
Added Sandbox (Demo Trading)

### Description of code - what bug does this fix / what feature does this add?

- [ X] - Tested
- [ ] - Changelog updated
- [ X] - Tests run and pass
- [ ] - Flake8 run and all errors/warnings resolved
- [ ] - Contributors file updated (optional)

### CODE REVIEW

**Comment by bmoscon** [comment]
looks like you need to rebase with the latest version from master and then make your changes @bandito1

**Comment by bmoscon** [comment]
looks good, but unfortunately the details of how connections are defined has changed, so this will need to be updated/rebased with master, and then re-tested.

**Comment by bandito1** [comment]
> looks good, but unfortunately the details of how connections are defined has changed, so this will need to be updated/rebased with master, and then re-tested.

I updated the latest git version, but get error with original okex module when subscribed to auth channel:
2022-01-06 10:33:20,149 : WARNING : OKEX.ws.2: encountered connection issue received 1005 (no status code [internal]); then sent 1005 (no status code [internal]) - reconnecting in 1.0 seconds...
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\cryptofeed\connection_handler.py", line 61, in _create_connection
    await self.subscribe(connection)
  File "C:\Python37\lib\site-packages\cryptofeed\exchanges\okex.py", line 394, in subscribe
    await connection.write(json.dumps(msg))
  File "C:\Python37\lib\site-packages\cryptofeed\connection.py", line 343, in write
    await self.conn.send(data)
  File "C:\Python37\lib\site-packages\websockets\legacy\protocol.py", line 619, in send
    await self.ensure_open()
  File "C:\Python37\lib\site-packages\websockets\legacy\protocol.py", line 929, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: received 1005 (no status code [internal]); then sent 1005 (no status code [internal])

**Comment by bmoscon** [comment]
@bandito1 - I made a change that I think will fix it. Can you rebase and test again?

**Comment by bmoscon** [comment]
@bandito1  - looking at your branch, your code is pretty out of date, so please make sure you rebase with the main repo

**Comment by bandito1** [comment]
> @bandito1 - looking at your branch, your code is pretty out of date, so please make sure you rebase with the main repo
I uploaded updated version. Please check it. I tested with demo account also, so sandbox working.

**Comment by bmoscon** [comment]
1. there are merge conflicts, please resolve them, 2. it looks like this is including other changes I made to the codebase as changes, probably because your fork was outdated and then you merged in those changes. Please rebase your fork so I can tell what the actual changes are.

**Comment by bmoscon** [comment]
@bandito1 can you rebase and re-test and then we can merge this in?

**Comment by bandito1** [comment]
> @bandito1 can you rebase and re-test and then we can merge this in?

Yes, now I testing.

**Comment by bmoscon** [comment]
seems like this PR is dead. If you ever get back to this, please feel free to open a new PR

**Pull request closed without merging**
