### PR TITLE
Rewrite Huobi to adapt market-by-price-incremental-update and impelem…

### PR DESCRIPTION
**Pull request by zhenpingfeng**
### Description of code - what bug does this fix / what feature does this add?
[Rewrite Huobi to adapt market-by-price-incremental-update and impelemet Huobi's Ticker channel.](https://github.com/bmoscon/cryptofeed/issues/431#issue-823895060)
- [ ] - Tested
- [ ] - Changelog updated
- [ ] - Contributors file updated (optional)
- [ ] - Tests run and pass
- [x] - Flake8 run and all errors/warnings resolved

### CODE REVIEW

**Comment by Jay54520** [comment]
Error for symbols not supported 20-level such as trxusdt. Maybe you need to support 150-level incremental channel  for these symbols.

> 5-level/20-level incremental channel only supports the following symbols at this stage - btcusdt,ethusdt,xrpusdt,eosusdt,ltcusdt,etcusdt,adausdt,dashusdt,bsvusdt, while 150-level incremental channel supports all symbols.

**Comment by zhenpingfeng** [comment]
Ok... I didn't notice that some symbols did not support 20-level, Huobi's API design is really strange.

**Comment by zhenpingfeng** [comment]
btw, although the depth snapshot refresh rate in the document is replaced by 1 second, it is actually still 100ms. so it is not meant to update to 150-level with a 100ms refresh rate.

**Comment by Jay54520** [comment]
> btw, although the depth snapshot refresh rate in the document is replaced by 1 second, it is actually still 100ms. so it is not being beneficial to update to mbp 150-level with a 100ms refresh rate.

Current interval of Huobi L2_BOOK is 1 second:
```
Timestamp: 1615463130.893 Feed: HUOBI Pair: TRX-USDT Book Bid Size is 150 Ask Size is 150
Timestamp: 1615463131.941 Feed: HUOBI Pair: TRX-USDT Book Bid Size is 150 Ask Size is 150
Timestamp: 1615463132.973 Feed: HUOBI Pair: TRX-USDT Book Bid Size is 150 Ask Size is 150
```

```
'''
Copyright (C) 2017-2021  Bryant Moscon - bmoscon@gmail.com
Please see the LICENSE file for the terms and conditions
associated with this software.
'''
from cryptofeed import FeedHandler
from cryptofeed.callback import BookCallback
from cryptofeed.defines import BID, ASK, L2_BOOK
from cryptofeed.exchanges import Huobi


async def book(feed, symbol, book, timestamp, receipt_timestamp):
    print(f'Timestamp: {timestamp} Feed: {feed} Pair: {symbol} Book Bid Size is {len(book[BID])} Ask Size is {len(book[ASK])}')


def main():
    fh = FeedHandler()

    callbacks = {L2_BOOK: BookCallback(book)}
    fh.add_feed(Huobi(symbols=['TRX-USDT'], channels=[L2_BOOK], callbacks=callbacks))

    fh.run()


if __name__ == '__main__':
    main()

```

**Comment by zhenpingfeng** [comment]
Ok, I mistook the swap's depth with spot depth, spot depth channel indeed refresh with 1 sec. I will change it to 150 level when I have time.

**Comment by zhenpingfeng** [comment]
I read the doc again, they said they will change the 150 level behavior in the future.

> In the near future, Huobi Global will align the update behavior of 150-level incremental channel with 5-level/20-level, which means while single side order book changed (either bid or ask), the update message will be no longer including a blank object for another side.

I think we should wait for the API to become stable.

**Comment by bmoscon** [comment]
@zhenpingfeng so is this ready to be tested and merged? Your last comment is unclear to me - are you suggesting we wait for API changes to merge?

**Comment by zhenpingfeng** [comment]
We should wait for the next update of the 150 level API. Then I make code adapt to it, after that we can merge.

**Comment by bmoscon** [comment]
@zhenpingfeng in that case I'll close this. Feel free to re-open or create a new PR when its ready to go

**Pull request closed without merging**
