### PR TITLE
Upbit book implementation fix

### PR DESCRIPTION
**Pull request by vdbelt**
As reported by @joelrich in https://github.com/bmoscon/cryptofeed/pull/240

### CODE REVIEW

**Comment by joelrich** [comment]
Does this remove zero entries from the order book?

**Comment by vdbelt** [comment]
Yes, it filters out zero entries from the book.

**Comment by joelrich** [comment]
@vdbelt Ok, thanks, now it makes more sense. I assume you have checked that bid and ask are no more overlapping?

**Comment by vdbelt** [comment]
Yes, I tested it on a branch with your outstanding PR applied. No more overlapping. 


I found another issue however when book deltas are enabled and max_depth is specified. Deltas would be provided disregarding the max_depth. Happens to the Huobi feeds as well. Seems to be an edge case that needs to be handled by the callback in feed.py. Will look at that.

**Pull request merged**
