### PR TITLE
GDAX channel name standardized, trades feed from ticker, book from level2 feed

### PR DESCRIPTION
**Pull request by MarechJ**
Following the comment in my open issue #4 , here's a candidate PR.

### CODE REVIEW

**Comment by bmoscon** [comment]
I'm not sure why you'd remove the L3 book support. At some point I want to let users choose between L2 and L3 books - for feeds that dont offer L2 books, I'd provide my own (i.e. top 100 (or whatever) levels from L3 book. I'm fine adding L2 book support, but not at the expense of L3 books

**Comment by MarechJ** [comment]
The L3 book should still work as before, unless I missed something? 
However I had trouble running it, when using all available pairs, the http calls in the _book_snapshot was hitting a rate limit (due to parallelization) i guess, and was crashing the whole thing. Also the format diverged from the bitfinex one (decimal keys instead of floats), and I wasn't sure if it's normal or not.

Please suggest edits, I'd rather contribute to this project rather than staying on my fork :) But I need a completely unified output format and aggregated book.

**Comment by bmoscon** [comment]
I'd be fine taking this (and maybe tweaking some of the things) but I'm not understanding why the versions are pinned. I really dont like version pinning unless there is a reason. Does some part of this break or not work with lower versions?

**Comment by MarechJ** [comment]
It's pinned to a minimum version updates will still go in (however that could cause trouble in the future). I did this because the websockets dependancy would not install for some reason, both in my docker setup and local virtualenv.

I'll start integrating you lib further in our project and might come back with similar PRs :)

How often do you push to pypi?

**Comment by bmoscon** [comment]
Ok, I'll get this merged sometime today. I'll release a new version to pypi sometime this weekend. In general I've only been pushing to pypi when there was a reason to (new feed, bugfix, or new functionality), but I can push whenever :)

**Comment by bmoscon** [comment]
sorry - another question. Why do you want the trades to come from the ticker? The matches feed is a true, real time source of ALL trades whereas the ticker is a batched channel so you wont really get a notification every time a match occurs. @MarechJ

**Comment by bmoscon** [comment]
@MarechJ ok reading over your issue again, it seems this is really "aggregated trades", right? Just wanted to make sure I'm understanding the intent

**Comment by MarechJ** [comment]
Yes, aggregated trades is what the trader I'm working with wants for some sophisticated quantitative analysis based on actual volumes. Ff the trades are aggretated from the taker point of view, it does not really change much and i'd say that 99% of the time you don't need to know all the small fills of a taker's side order. Maybe for keeping the lib friendly we should establish some standard definitions of the channels types (whether they are emulated or not), something like:
- ticker: best bid/ask, 24h volume (rolling), last price
- trades (Aggregated), buy/sell (taker's side), average price (VWAP if possible), trade size, timestamp 
- matches (non aggregated trades): same as above but with exact prix
- book: (aggregated) top 50-100 best bid/ask, price, size, nb of trades (optionnal), timestamp
- full_book: same as above but non aggregated, timestamp

For storage performance it'd also be preferable to have the 'pair' in the book callback other when need to iterate on all the pairs even though only one has been updated.

For good UX also have the raw_message passed in the callback for every channel.

And last remark, the current format of the book with price as keys is handy for updating it, but not for using it, i need to sort it before storing it or before using it for analysis this could be problematic for strategies relying on perfs.

Let me know what you think.
Sorry if there are a lot of typos I'm in a bit of a rush :D 

Cheers

**Comment by bmoscon** [comment]
everything you've suggested, except raw message request, I've already started working on in a branch, `standardize`

**Comment by MarechJ** [comment]
Ok, great. If you have a detailed plan you can assign a few tickets to me, I can tackle some stuff next week. Thx

**Comment by MarechJ** [comment]
I made a mistake converting prices to float, you actually use Decimal in other exchanges.

**Pull request merged**
