### PR TITLE
periodic snapshots, L3_BOOK_UPDATE, L3_BOOK sig changes

### PR DESCRIPTION
**Pull request by rjbks**
Level 3 Book Update callbacks:

- for most granular messages currently provided by gemini and gdax APIs.

- Signature: feed, pair, msg_type, timestamp, sequence, side, price, size (most basic info needed to rebuild book)

Level 3 Book callback:

- Signature change to include sequence and timestamp since some APIs provide only one or the other (or neither) which may be needed to rebuild book from certain points in time when storing snapshots periodically

L3 Periodic Snapshots:

- Feed.synthesize_feed method added to schedule calls to REST endpoints to approximate a websocket feed. Works in conjunction with Feed.intervals attribute to schedule at specified intervals

- Feed.default_interval is the value provided in the Feed.intervals default dict if it is not explicitly set

- Feed.intervals: default dict storing the desired schedule intervals for any Feed methods called periodically by Feed.synthesize_feed

Changes to Feed._book_snapshot in each Feed subclass:

- fetches a snapshot for 1 pair (as opposed to all pairs in self.pairs) at a time seeing as Feed.synthesize_feed approximates a websocket feed and messages should be specific to pair and channel

### CODE REVIEW

**Comment by rjbks** [comment]
Apologies in advance for the terrible commit history but the issues with the last PR came from a botched attempt to clean it up with a rebase and some trouble with cleanup attempts again today.

**Comment by bmoscon** [comment]
Thanks! I’ll take a look today.

**Comment by bmoscon** [comment]
looks good @rjbks . I try not to merge anything in unless I've run it on my servers for 48+ hours so I'm going to start this up and test it out. Thanks for this!

**Comment by bmoscon** [comment]
@rjbks yes you can clean up the commit history if you want. I think these changes are all fine, I'm just not sure what the purpose of the synthesized feed is for? Is this for sending the periodic full books?

**Comment by bmoscon** [comment]
Appreciate your work on this - but I never heard back on my questions/concerns on here or on the other PR, so closing. Feel free to open new tickets or PRs if you want to address the changes I made in my PR

**Pull request closed without merging**
