### PR TITLE
WIP: Fix bug in BackendFuturesIndexCallback and bug in FuturesIndexPostgres and OpenInterestPostgres methods

### PR DESCRIPTION
**Pull request by qinghuangchan**
### Description of code - what bug does this fix / what feature does this add?

Previously, I added a futures_index type for ByBit. Somehow committed a typo along with it. 

Also, discovered that the FuturesIndexPostgres and OpenInterestPostgres method both needed some extra extraction of the data dict in order to be inserted correctly. 

- [x] - Tested
- [x] - Changelog updated
- [ ] - Tests run and pass
- [ ] - Flake8 run and all errors/warnings resolved
- [ ] - Contributors file updated (optional)

### CODE REVIEW

**Comment by bmoscon** [comment]
@qinghuangchan was going to merge this, did you close it on accident?

**Comment by qinghuangchan** [comment]
sorry about the messy commits... not particularly well-versed in git and can't seem to condense them..  i hope you don't mind! :/

**Comment by bmoscon** [comment]
@qinghuangchan i always squash the commits, so it all goes to one single commit

**Comment by qinghuangchan** [comment]
roger. pls go for merge then. thanks!

**Pull request merged**
