### PR TITLE
Add guard against non-supported asyncio add_signal_handler() on windows platforms

### PR DESCRIPTION
**Pull request by davidtwomey**
### Description of code - what bug does this fix / what feature does this add?

Windows does not support asyncio loop.add_signal_handler() (See: https://docs.python.org/3/library/asyncio-platforms.html)

Get a NotImplementedError when running from windows.

This PR just adds a simple check if we are on a windows platform to avoid adding signal handles.

- [x] - Tested
- [x] - Changelog updated
- [ ] - Tests run and pass
- [ ] - Flake8 run and all errors/warnings resolved
- [ ] - Contributors file updated (optional)

### CODE REVIEW

**Comment by olibre** [comment]
Hi @davidtwomey 
I cannot test Cryptofeed using Windows but I have read this SO answer:
https://stackoverflow.com/a/54886771

Maybe a better workaround is to use the classic function `signal.signal()` on Windows.

You may test the following code:

```py
for signal in SIGNALS:
    signal.signal(signal, handle_stop_signals)
```

in lieu of the current one:

```py
for signal in SIGNALS:
    loop.add_signal_handler(signal, handle_stop_signals)
```

Please give us some feedback. :wink:

**Comment by davidtwomey** [comment]
Hi @olibre,

Yes that could work! 
Are you proposing to a) switch completely to `signal.signal` or b) only if on a windows (and therefore keep the `loop.add_signal_handler` generally)?

**Comment by bmoscon** [comment]
@davidtwomey in the conditional you added you can probably just substitute 

```
for signal in SIGNALS:
    signal.signal(signal, handle_stop_signals)
```
for the return statement you have

**Comment by olibre** [comment]
Hi @davidtwomey 
I was thinking b) keep the `loop.add_signal_handler()` generally but use `signal.signal()` only if on windows :+1:

**Comment by davidtwomey** [comment]
Ok `signal.signal` is now implemented for windows. 

Note `handle_stop_signals` has to now accept *args or you get the following (on windows):

```
[ERROR] Encountered error handle_stop_signals() takes 0 positional arguments but 2 were given...closing
```

**Review by bmoscon — APPROVED** [review]

**Comment by bmoscon** [comment]
thanks for the PR!

**Pull request merged**
